### PR TITLE
Python 3.5, 3.6, and 3.7 support

### PR DESCRIPTION
**Pull request by willprice**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This overhauls the conda recipe to build python 3.5 (not officially supported by conda-forge), 3.6, 3.7 binaries on osx and linux.

### CODE REVIEW

**Comment by willprice** [comment]
One thing to note is to support python 3.5 you'll have to set the `python` key in `$CONDA_PREFIX/conda_build_config.yaml` like so:

```
python:
  - 3.5
  - 3.6
  - 3.7  # [(environ.get('CF_MAX_PY_VER', '') >= '37')]
```

Before running `conda-smithy regenerate --commit` to regenerate the conda-forge files.

**Comment by willprice** [comment]
Travis builds: https://travis-ci.com/willprice/lintel-feedstock/builds/96023891?utm_medium=notification&utm_source=email
Circle builds: https://circleci.com/gh/willprice/lintel-feedstock/tree/master

**Comment by willprice** [comment]
Note, this should be merged in *instead* of https://github.com/conda-forge/lintel-feedstock/pull/1 from which I have integrated the changes (into `conda-forge.yaml`)

**Comment by willprice** [comment]
@dukebw/@sdvillal,
When you've got a chance could have take a look at this? Cheers and happy new year :) :tada:

**Comment by dukebw** [comment]
Hi @willprice, I took a look and it's reasonable -- although I have no experience with Conda recipes as @sdvillal set this feedstock up. Is there anything I need to do for #2 to get merged?

**Comment by willprice** [comment]
Hi @dukebw,
Thanks for taking a look at this. All you need to do is merge this in then conda-forge takes care of the rest.

**Comment by dukebw** [comment]
Done! Sorry, I needed to join the conda-forge organization for the merge button to appear.

**Pull request merged**
